dist: xenial
group: edge
jobs:
  include:
    - language: python
      python: '3.7'
      cache: pip
      install:
        - pip install pre-commit
      script:
        - pre-commit run --all-files
