dist: xenial
group: edge

stages:
  - name: Tests

jobs:
  include:

    - stage: Tests
      name: Pre-commit tests
      language: python # pre-commit
      python:
        - 3.8
      install:
        - pip install pre-commit
      script:
        - pre-commit run --all-files
