name: push-pipeline
on:
  push:
    branches:
      - master
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.2
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APPNAME }}
          dockerfile_directory: ./server
          dockerfile_name: Dockerfile
          docker_options: '--no-cache'
          process_type: web
